nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['*']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'Signature', 'once', 'time', 'platform', 'parameter','token','Origin', 'X-Requested-With', 'Accept','current-version']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': null
