# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    page.page: 1
    page.size: 15
    # for JWT
    jwt.private: '/config/certificate/jwt/rsa_private.pem'
    jwt.public: '/config/certificate/jwt/rsa_public.pem'
    # for sign with request
    sign.private: '/config/certificate/sign/rsa_private.pem'
    sign.public: '/config/certificate/sign/rsa_public.pem'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc._defaults:
        bind:
            $page: '%page.page%'
            $size: '%page.size%'
            $projectDirectory: "%kernel.project_dir%"

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # design exception handler choose one of these 'event_listener' or 'event_subscriber'
#    App\EventListener\Exception:
#        tags:
#            - { name: kernel.event_listener, event: kernel.exception }
#        arguments:
#            $env: '%env(APP_ENV)%'
#            $from: '%env(FROM_EMAIL)%'
#            $dev: '%env(DEV_EMAIL)%'

    App\EventSubscriber\Exception:
        tags:
            - { name: kernel.event_subscriber, event: kernel.exception }
        arguments:
            $env: '%env(APP_ENV)%'
            $from: '%env(FROM_EMAIL)%'
            $dev: '%env(DEV_EMAIL)%'

    App\EventListener\Request:
        tags:
            - { name: kernel.event_listener, event: kernel.request }
        arguments:
            $env: '%env(APP_ENV)%'

    Symfony\Bundle\TwigBundle\Controller\ExceptionController: '@twig.controller.exception'

    App\Service\VerificationCode:
        arguments:
            $from: '%env(FROM_EMAIL)%'

    App\Service\Signature:
        arguments:
            $public: '%sign.public%'
            $private: '%sign.private%'
            $timeout: 7000
            $onceExpire: 60

    App\Service\Token:
        arguments:
            $public: '%jwt.public%'
            $private: '%jwt.private%'
            $type: 'RS256'
            $expire: 86400